---
- hosts: localhost
  connection: local

  tasks:
  - name: create a bucket
    gcp_storage_bucket:
      name: "{{ bucket_name }}"
      project: "{{ project_id }}"
      auth_kind: serviceaccount
      #service_account_file: "/home/mbandi-google/gcp-batch-project-key.json"
      state: "{{ state }}"
