---
- hosts: localhost
  connection: local

  tasks:
  - name: create a bucket
    gcp_storage_bucket:
      name: jjtech-gcp-ansible-storage-bucket
      project: sonic-wavelet-350400
      auth_kind: serviceaccount
      #service_account_file: "/home/mbandi-google/gcp-batch-project-key.json"
      state: present
